from database.models import db, Product, ProductWarning, BannedIngredient
from datetime import datetime


def seed_database():
    """Seed database with sample Indian products"""

    products = [
        # ============ FOOD PRODUCTS ============
        Product(
            barcode='8901058851854',
            name='Parle-G Gold Biscuits',
            brand='Parle',
            category='food',
            subcategory='biscuits',
            description='Glucose biscuits enriched with vitamins',
            fssai_license='10013041000157',
            manufacturer='Parle Products Pvt Ltd',
            manufacturer_address='Vile Parle East, Mumbai 400057, Maharashtra, India',
            country_of_origin='India',
            mrp=30.0,
            net_weight='100g',
            shelf_life='9 months',
            storage_instructions='Store in cool and dry place',
            serving_size='4 biscuits (28g)',
            energy_kcal=124.0,
            protein_g=1.8,
            carbohydrates_g=19.6,
            sugar_g=6.0,
            fat_g=4.2,
            saturated_fat_g=2.1,
            trans_fat_g=0.0,
            fiber_g=0.5,
            sodium_mg=80.0,
            is_vegetarian=True,
            veg_nonveg_mark='green_dot',
            ingredients_list='Wheat Flour, Sugar, Edible Vegetable Oil, Invert Syrup, Leavening Agents, Milk Solids, Salt, Emulsifier, Dough Conditioner',
            allergens='Contains wheat, milk',
            contains_dairy=True,
            data_source='local_db',
        ),
        Product(
            barcode='8901262150255',
            name='Maggi 2-Minute Noodles Masala',
            brand='Nestle',
            category='food',
            subcategory='instant_noodles',
            description='Instant noodles with masala flavour',
            fssai_license='10013061006476',
            manufacturer='Nestle India Ltd',
            manufacturer_address='Nestle House, Jacaranda Marg, M Block, DLF City Phase-II, Gurugram, Haryana',
            country_of_origin='India',
            mrp=14.0,
            net_weight='70g',
            shelf_life='8 months',
            serving_size='1 pack (70g)',
            energy_kcal=313.0,
            protein_g=7.3,
            carbohydrates_g=43.6,
            sugar_g=1.0,
            fat_g=12.0,
            saturated_fat_g=5.6,
            trans_fat_g=0.0,
            fiber_g=2.0,
            sodium_mg=860.0,
            is_vegetarian=True,
            veg_nonveg_mark='green_dot',
            ingredients_list='Wheat Flour, Palm Oil, Starch, Salt, Onion Powder, Spices, Mineral, Garlic Powder, Turmeric',
            allergens='Contains wheat, may contain traces of soy',
            data_source='local_db',
        ),
        Product(
            barcode='8901030793424',
            name='Amul Taaza Toned Milk',
            brand='Amul',
            category='food',
            subcategory='dairy',
            description='Homogenised Toned Milk',
            fssai_license='10011011000234',
            manufacturer='Gujarat Cooperative Milk Marketing Federation Ltd (GCMMF)',
            manufacturer_address='Amul Dairy Road, Anand 388001, Gujarat, India',
            country_of_origin='India',
            mrp=27.0,
            net_volume='500ml',
            shelf_life='180 days',
            storage_instructions='Store under refrigeration (4°C or below)',
            serving_size='200ml',
            energy_kcal=120.0,
            protein_g=6.0,
            carbohydrates_g=9.0,
            sugar_g=9.0,
            fat_g=6.0,
            saturated_fat_g=3.8,
            sodium_mg=100.0,
            cholesterol_mg=12.0,
            is_vegetarian=True,
            veg_nonveg_mark='green_dot',
            ingredients_list='Toned Milk',
            allergens='Contains milk',
            contains_dairy=True,
            data_source='local_db',
        ),
        Product(
            barcode='8901499011022',
            name='Haldiram\'s Aloo Bhujia',
            brand='Haldiram\'s',
            category='food',
            subcategory='snacks',
            description='Spicy potato noodle snack',
            fssai_license='10014011000215',
            manufacturer='Haldiram Snacks Pvt Ltd',
            manufacturer_address='A-9, Udyog Nagar, Rohtak Road, New Delhi 110041',
            country_of_origin='India',
            mrp=45.0,
            net_weight='200g',
            shelf_life='6 months',
            serving_size='30g',
            energy_kcal=167.0,
            protein_g=4.0,
            carbohydrates_g=15.5,
            fat_g=10.0,
            sodium_mg=290.0,
            is_vegetarian=True,
            veg_nonveg_mark='green_dot',
            ingredients_list='Potato, Gram Flour, Edible Oil, Spices, Salt, Citric Acid',
            data_source='local_db',
        ),

        # ============ MEDICINES ============
        Product(
            barcode='8901790753456',
            name='Crocin Advance 500mg',
            brand='GSK',
            category='medicine',
            subcategory='analgesic',
            description='Paracetamol tablets for pain and fever relief',
            drug_license_number='KD-839',
            manufacturer='GlaxoSmithKline Pharmaceuticals Ltd',
            manufacturer_address='Dr. Annie Besant Road, Worli, Mumbai 400030',
            country_of_origin='India',
            mrp=33.51,
            net_weight='20 tablets',
            shelf_life='36 months',
            storage_instructions='Store below 30°C. Protect from moisture.',
            composition='Paracetamol IP 500mg',
            dosage='Adults: 1-2 tablets every 4-6 hours. Max 8 tablets in 24 hours.',
            side_effects='Nausea, Allergic reactions (rare), Liver damage (overdose)',
            contraindications='Liver disease, Alcohol dependence, Known hypersensitivity',
            prescription_required=False,
            schedule='OTC',
            ingredients_list='Paracetamol IP 500mg, Maize Starch, Povidone, Potassium Sorbate, Stearic Acid',
            data_source='local_db',
        ),
        Product(
            barcode='8901790757123',
            name='Dolo 650mg',
            brand='Micro Labs',
            category='medicine',
            subcategory='analgesic',
            description='Paracetamol tablets 650mg for fever and pain',
            drug_license_number='KTK/28/113/2006',
            manufacturer='Micro Labs Limited',
            manufacturer_address='No. 27, Race Course Road, Bangalore 560001',
            country_of_origin='India',
            mrp=33.62,
            net_weight='15 tablets',
            shelf_life='24 months',
            storage_instructions='Store below 25°C in a dry place. Protect from light.',
            composition='Paracetamol IP 650mg',
            dosage='Adults: 1 tablet 3-4 times a day. Max dose: 4g/day',
            side_effects='Nausea, vomiting, allergic skin reactions',
            contraindications='Severe hepatic impairment, Hypersensitivity to paracetamol',
            prescription_required=False,
            schedule='OTC',
            data_source='local_db',
        ),
        Product(
            barcode='8901790789456',
            name='Azithral 500mg',
            brand='Alembic',
            category='medicine',
            subcategory='antibiotic',
            description='Azithromycin tablets for bacterial infections',
            drug_license_number='G/25/790',
            manufacturer='Alembic Pharmaceuticals Ltd',
            manufacturer_address='Alembic Road, Vadodara 390003, Gujarat',
            country_of_origin='India',
            mrp=103.00,
            net_weight='3 tablets',
            shelf_life='24 months',
            composition='Azithromycin Dihydrate IP equiv to Azithromycin 500mg',
            dosage='As directed by physician. Usually 500mg once daily for 3 days.',
            side_effects='Diarrhea, nausea, abdominal pain, vomiting',
            contraindications='Hypersensitivity to azithromycin or any macrolide antibiotic',
            prescription_required=True,
            schedule='H',
            data_source='local_db',
        ),

        # ============ NUTRACEUTICALS ============
        Product(
            barcode='8901689152012',
            name='Himalaya Ashvagandha',
            brand='Himalaya Wellness',
            category='nutraceutical',
            subcategory='herbal_supplement',
            description='Pure Herbs Ashvagandha for stress relief and energy',
            fssai_license='10016011003127',
            ayush_license='ISM/MFG/CT/0021',
            manufacturer='The Himalaya Drug Company',
            manufacturer_address='Makali, Bangalore 562162, Karnataka, India',
            country_of_origin='India',
            mrp=230.0,
            net_weight='60 tablets',
            shelf_life='36 months',
            storage_instructions='Store in a cool dry place away from direct sunlight',
            usage_instructions='1 tablet twice daily or as directed by the physician',
            composition='Ashvagandha (Withania somnifera) root extract 250mg',
            is_vegetarian=True,
            veg_nonveg_mark='green_dot',
            ingredients_list='Ashvagandha root extract, Excipients',
            data_source='local_db',
        ),
        Product(
            barcode='8901689157891',
            name='Dabur Chyawanprash',
            brand='Dabur',
            category='nutraceutical',
            subcategory='ayurvedic',
            description='Ayurvedic health supplement with Amla and herbs',
            fssai_license='10014011000198',
            ayush_license='ISM/MFG/UT/0008',
            manufacturer='Dabur India Ltd',
            manufacturer_address='8/3, Asaf Ali Road, New Delhi 110002',
            country_of_origin='India',
            mrp=325.0,
            net_weight='500g',
            shelf_life='24 months',
            usage_instructions='Adults: 1 tablespoon twice daily. Children: 1 teaspoon twice daily.',
            serving_size='15g',
            energy_kcal=42.0,
            carbohydrates_g=10.2,
            sugar_g=6.5,
            is_vegetarian=True,
            veg_nonveg_mark='green_dot',
            ingredients_list='Amla, Sugar, Ghee, Sesame Oil, Honey, Ashwagandha, Pippali, Giloy, Tulsi, and 40+ Ayurvedic herbs',
            data_source='local_db',
        ),

        # ============ SKINCARE ============
        Product(
            barcode='8901030697289',
            name='Lakme Sun Expert SPF 50',
            brand='Lakme',
            category='skincare',
            subcategory='sunscreen',
            description='Ultra Matte Lotion Sunscreen SPF 50 PA+++',
            manufacturer='Hindustan Unilever Ltd',
            manufacturer_address='Unilever House, B.D. Sawant Marg, Chakala, Andheri East, Mumbai 400099',
            country_of_origin='India',
            mrp=399.0,
            net_weight='100ml',
            shelf_life='24 months',
            storage_instructions='Store in a cool, dry place. Avoid direct sunlight.',
            usage_instructions='Apply generously 15 minutes before sun exposure. Reapply every 2 hours.',
            spf_value=50,
            skin_type='All skin types',
            paraben_free=False,
            cruelty_free=False,
            ingredients_list='Aqua, Ethylhexyl Methoxycinnamate, Dimethicone, Titanium Dioxide, Zinc Oxide, Glycerin, Niacinamide',
            data_source='local_db',
        ),
        Product(
            barcode='8906009540115',
            name='Mamaearth Vitamin C Face Wash',
            brand='Mamaearth',
            category='skincare',
            subcategory='face_wash',
            description='Vitamin C Face Wash with Vitamin C and Turmeric',
            manufacturer='Honasa Consumer Pvt Ltd',
            manufacturer_address='Plot No. GH-04, Sector 10, Greater Noida West, UP 201306',
            country_of_origin='India',
            mrp=349.0,
            net_weight='100ml',
            shelf_life='24 months',
            usage_instructions='Apply on wet face, massage gently, rinse off',
            skin_type='All skin types',
            paraben_free=True,
            sulphate_free=True,
            cruelty_free=True,
            ingredients_list='Aqua, Sodium Lauroyl Sarcosinate, Cocamidopropyl Betaine, Vitamin C, Turmeric Extract, Aloe Vera',
            data_source='local_db',
        ),

        # ============ HAIRCARE ============
        Product(
            barcode='8901030718960',
            name='Dove Hair Fall Rescue Shampoo',
            brand='Dove',
            category='haircare',
            subcategory='shampoo',
            description='Hair Fall Rescue Shampoo with Nutrilock Actives',
            manufacturer='Hindustan Unilever Ltd',
            manufacturer_address='Unilever House, Andheri East, Mumbai 400099',
            country_of_origin='India',
            mrp=260.0,
            net_weight='340ml',
            shelf_life='24 months',
            usage_instructions='Apply to wet hair, lather, rinse thoroughly',
            skin_type='All hair types',
            paraben_free=True,
            sulphate_free=False,
            ingredients_list='Aqua, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Sunflower Seed Oil, Dimethicone, Guar Hydroxypropyltrimonium Chloride',
            data_source='local_db',
        ),
        Product(
            barcode='8904245700577',
            name='Biotique Bio Kelp Shampoo',
            brand='Biotique',
            category='haircare',
            subcategory='shampoo',
            description='Fresh Growth Protein Shampoo for Falling Hair',
            manufacturer='Bio Veda Action Research Co.',
            manufacturer_address='A-21, Industrial Area, Baddi, Solan, HP 173205',
            country_of_origin='India',
            mrp=199.0,
            net_weight='190ml',
            shelf_life='36 months',
            usage_instructions='Apply to wet hair, massage gently, leave for 2 minutes, rinse',
            paraben_free=True,
            sulphate_free=True,
            cruelty_free=True,
            is_organic=True,
            ingredients_list='Kelp Extract, Neem, Bhringraj, Peppermint Oil, Natural Protein Complex',
            data_source='local_db',
        ),
    ]

    banned_ingredients = [
        BannedIngredient(
            ingredient_name='Potassium Bromate',
            category='food',
            ban_type='banned',
            regulatory_body='FSSAI',
            regulation_reference='FSSAI Order dated 20/06/2016',
            reason='Classified as possibly carcinogenic to humans (Group 2B) by IARC',
        ),
        BannedIngredient(
            ingredient_name='Calcium Bromate',
            category='food',
            ban_type='banned',
            regulatory_body='FSSAI',
            reason='Carcinogenic potential',
        ),
        BannedIngredient(
            ingredient_name='Mercury and its compounds',
            category='cosmetic',
            ban_type='banned',
            regulatory_body='CDSCO',
            reason='Toxic to nervous system, kidneys',
        ),
        BannedIngredient(
            ingredient_name='Hydroquinone (>2%)',
            category='cosmetic',
            ban_type='restricted',
            max_allowed='2% in cosmetic preparations',
            regulatory_body='CDSCO',
            reason='Skin irritation, ochronosis at higher concentrations',
        ),
        BannedIngredient(
            ingredient_name='Lead Acetate',
            category='cosmetic',
            ban_type='banned',
            regulatory_body='CDSCO',
            reason='Toxic heavy metal compound',
        ),
        BannedIngredient(
            ingredient_name='Nimesulide (for children)',
            category='drug',
            ban_type='banned',
            regulatory_body='CDSCO',
            regulation_reference='Gazette Notification GSR 82(E), 2011',
            reason='Hepatotoxicity risk in children under 12',
        ),
        BannedIngredient(
            ingredient_name='Phenylpropanolamine',
            category='drug',
            ban_type='banned',
            regulatory_body='CDSCO',
            reason='Risk of haemorrhagic stroke',
        ),
    ]

    for product in products:
        existing = Product.query.filter_by(barcode=product.barcode).first()
        if not existing:
            db.session.add(product)

    for ingredient in banned_ingredients:
        existing = BannedIngredient.query.filter_by(
            ingredient_name=ingredient.ingredient_name
        ).first()
        if not existing:
            db.session.add(ingredient)

    db.session.commit()
    print(f"✅ Seeded {len(products)} products and {len(banned_ingredients)} banned ingredients")